echo Starting SXServiseCLI 2024...
echo INFO: By StasX...
echo Updating pip...
python -m pip install --upgrade pip
echo Libraries have been updated...
echo Starting SXServiseCLI 2024...
python SXServiseCLI.py
