commands_map = {
    "ssh": "ssh",
    "ftp": "ftp",
    "init": "init",
    "help": "help",
    "info": "info",
    "support": "support",
    "pers": "pers",
    "config": "config",
    "whois": "whois",
    "pscan": "pscan",
    "ping": "ping",
    "upgrade": "upgrade",
    "genai":"genai",
    "device": "device",
    "faker": "faker",
    "netmon": "netmon",
    "ai": "ai",
    "ip":"ip",
    "clear": "clear",
    "mac": "mac",
    "db": "db",
    "networkinfo": "networkinfo",
    "about":"about",
    "qrcode":"qrcode",
    "api":"api",
    "speedtest":"speedtest",
    "cpu":"cpu",
    "gpu":"gpu",
    "search":"search",
    ".":".",
    "status":"status",
    "mediapipe":"mediapipe"
}
command_list=["ssh", "ftp", "init", "help", "info", "support", "pers", "config", "whois", "pscan", "ping", "upgrade", "genai", "device", "faker","netmon","ai","ip","clear","mac","db","networkinfo","about","qrcode", "api","speedtest","cpu","gpu", "search", ".", "status", "mediapipe"]